;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2013/5/18 21:05:57

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

IDH_1001=src\‘∂≥Ã≈‰÷√.html	; ‘∂≥Ã≈‰÷√.html
